name: FacetWP Updater

# Run this workflow twice daily
on:
  # schedule:
  #   - cron: '0 */12 * * *'
  workflow_dispatch:

env:
  PACKAGE_SLUG: facetwp

jobs:
  update:
    name: Fetch and check versions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Use FacetWP API to find download link for latest
      - name: Get download link from FacetWP API
        id: FacetWPAPIResponse
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://api.facetwp.com'
          contentType: 'application/x-www-form-urlencoded'
          method: 'POST'
          data: '{"action": "check_plugins", "slugs": "${{env.PACKAGE_SLUG}}", "license": "${{secrets.FACETWP_KEY}}"}'

      # uncomment to debug or see other "offerings" your license can download
      - name: Show Response
        run: echo ${{ steps.FacetWPAPIResponse.outputs.response }}

      # Fetch latest version of FacetWP to download
      - name: Fetch
        run: wget '${{fromJson(steps.FacetWPAPIResponse.outputs.response).slugs[env.PACKAGE_SLUG].package}}' -O package.zip

      # Get the latest plugin and compare versions, commit if necessary
      - uses: ./.github/actions/update-plugin
        name: Update WordPress Plugin
        with:
          package-slug: ${{ env.PACKAGE_SLUG }}
          package-file-name: package.zip
