name: Gravity Forms Addon Updater

# Run this workflow twice daily
on:
  # schedule:
  #   - cron: '0 */12 * * *'
  workflow_dispatch:

env:
  PACKAGE_SLUG: gravityformsrecaptcha

jobs:
  update:
    name: Fetch and check versions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Use GravityForms API to find download link for latest
      - name: Get download link from GravityForms API
        id: GravityFormsAPIResponse
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://www.gravityhelp.com/wp-content/plugins/gravitymanager/version.php?nocache=1&version=2&key=${{secrets.GRAVITYFORMS_KEY}}'

      # Fetch latest version of Gravity Forms add-on to download
      - name: Fetch
        run: wget '${{fromJson(steps.GravityFormsAPIResponse.outputs.response).offerings[env.PACKAGE_SLUG].url_latest}}' -O package.zip

      # Get the latest plugin and compare versions, commit if necessary
      - uses: ./.github/actions/update-plugin
        name: Update WordPress Plugin
        with:
          package-slug: ${{ env.PACKAGE_SLUG }}
          package-file-name: package.zip
